---
- name: Configuring Nomad Server and Client
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Upgrading packages
      yum:
        name: "*"
        state: latest

    - name: Installing net-tools
      yum:
        name: net-tools
        state: latest

    - name: Installing vim
      yum:
        name: vim
        state: latest

    - name: Installing tmux
      yum:
        name: tmux
        state: latest  

    - name: Installing jq
      yum:
        name: jq
        state: latest 

    - name: Installing yum-utils
      yum:
        name: yum-utils
        state: latest

    - name: Adding nomad repo
      shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

    - name: Installing nomad
      yum:
        name: nomad
        state: latest
    
    - name: Installing docker
      shell: amazon-linux-extras install docker

    - name: Starting docker
      service:
        name: docker
        enabled: yes
        state: started