---
- name: Configuring EC2
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Upgrading packages
      yum:
        name: "*"
        state: latest

    - name: Installing net-tools
      yum:
        name: net-tools
        state: latest

    - name: Installing vim
      yum:
        name: vim
        state: latest

    - name: Installing tmux
      yum:
        name: tmux
        state: latest

    - name: Installing yum-utils
      yum:
        name: yum-utils
        state: latest

    - name: Adding nomad repo
      shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

    - name: Installing nomad
      yum:
        name: nomad
        state: latest

    # - name: Creating nomad config directory
    #   file:
    #     path: /opt/nomad-configs
    #     state: directory
    #     mode: "u=rw,g=rw,o=rw"

    - name: Copying files from /tmp/nomad-configs to /opt/nomad-configs
      copy:
        src: /tmp/nomad-configs
        dest: /opt/nomad-configs
        mode: u=rw,g=rw,o=rw
