---
- name: Configuring EC2
  hosts: localhost
  connection: local
  become: true
    
  tasks: 
   - name: Upgrading packages
     yum:
       name: "*"
       state: latest
  
   - name: Installing net-tools
     yum:
       name: net-tools
       state: latest
       update_cache: yes  

   - name: Installing vim
     yum:
       name: vim
       state: latest
       update_cache: yes  

   - name: Installing tmux
     yum:
       name: tmux
       state: latest
       update_cache: yes
   
   - name: Installing yum-utils
     yum:
       name: yum-utils
       state: latest
       update_cache: yes
  
   - name: Adding Nomad repo 
     yum_repository:
       name: nomad
       description: Hashicorp Nomad repo 
       baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo 