---
- name: Initializing Nomad Client
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Upgrading packages
      yum:
        name: "*"
        state: latest

    - name: Overwrite a nomad client config file
      copy:
        src: "/tmp/nomad-configs/client.hcl"
        dest: "/etc/nomad.d/nomad.hcl"

    - name: Set client name
      lineinfile:
        path: "/etc/nomad.d/nomad.hcl"
        regexp: "^name = "
        line: 'name = "{{hostname}}"'
        backup: yes

    - name: Set Nomad server ip address or hostname
      lineinfile:
        path: "/etc/nomad.d/nomad.hcl"
        regexp: "^      IP_ADDRESS_OR_URL"
        line: "      {{ip}}"

    - name: Initializing nomad client
      service:
        name: nomad
        enabled: yes
        state: started
