---
- name: Initializing Nomad Server
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Upgrading packages
      yum:
        name: "*"
        state: latest

    - name: Updating SSM Parameter with server public hostname
      shell: aws ssm put-parameter --name nomad-server --value {{public}} --overwrite --region us-east-2

    - name: Overwrite a nomad server config file
      copy:
        src: "/tmp/nomad-configs/server.hcl"
        dest: "/etc/nomad.d/nomad.hcl"

    - name: Set server name
      lineinfile:
        path: "/etc/nomad.d/nomad.hcl"
        regexp: "^name = "
        line: 'name = "{{hostname}}"'
        backup: yes

    - name: Initializing nomad server
      service:
        name: nomad
        enabled: yes
        state: started
